apiVersion: v1
kind: Pod
metadata:
  name: egress-internalip
  labels:
    name: "egress-internalip"
  annotations:
    pod.network.openshift.io/assign-macvlan: "true"
spec:
  containers:
  - name: egress-router
    image: openshift/origin-egress-router
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE 
      value: 192.168.1.111
    - name: EGRESS_GATEWAY 
      value: 192.168.1.1
    - name: EGRESS_DESTINATION 
      value: 192.168.1.6

