apiVersion: v1
kind: Pod
metadata:
  name: mkdir-seccomp-profile
  labels:
    name: "mkdir-seccomp-profile"
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "localhost/mkdir.json"
spec:
  containers:
  - name: "mkdir-seccomp-profile"
    image: jtudela/net-utils
    command: ["/usr/bin/sleep","10000"]
  restartPolicy: Never
