apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-qos-limited
  annotations:
    kubernetes.io/ingress-bandwidth: "1M"
    kubernetes.io/egress-bandwidth: "1M"
  labels:
    name: "iperf-client-qos-limited"
spec:
  containers:
  - name: "iperf-client-qos-limited"
    image: jtudela/net-utils
    command: ["/usr/bin/iperf","-u","-f","K","-p","5001","-n","1M","-c","192.168.1.6"]
  restartPolicy: Never
